# Generated by Django 4.2.9 on 2025-07-16 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_bucket', models.CharField(choices=[('lighthearted', 'Lighthearted'), ('up_for_anything', 'Up for Anything'), ('deep', 'Deep Conversation')], max_length=20)),
                ('mood_slider', models.FloatField(help_text='0.0 → 1.0 position of slider')),
                ('mood_text', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('timer_seconds', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
