# Generated by Django 4.2.9 on 2025-07-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibe',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='vibe',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
    ]
