# Generated by Django 4.2.9 on 2025-07-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0002_alter_vibe_latitude_alter_vibe_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='vibe',
            name='status',
            field=models.CharField(choices=[('paused', 'Paused'), ('cancelled', 'Cancelled'), ('running', 'Running'), ('pauseandhide', 'Paused And Hide')], default='running', max_length=20),
        ),
    ]
